var chrtorelchr=[],chrtorelchr_amount={},blockdata_det=[],b_pos={1:{i:3,j:4},2:{i:1,j:4},3:{i:3,j:3},4:{i:1,j:3},5:{i:3,j:5},6:{i:1,j:5},7:{i:3,j:2},8:{i:1,j:2},9:{i:3,j:6},10:{i:1,j:6},11:{i:3,j:1},12:{i:1,j:1},13:{i:3,j:7},14:{i:1,j:7},15:{i:4,j:1},16:{i:4,j:2},17:{i:4,j:3},18:{i:4,j:4},19:{i:4,j:5},20:{i:4,j:6},21:{i:4,j:7}};
function explore_detail(a){1>a.length||setTimeout(function(){svg.select("#edgesg").remove();svg.select("#genesg").remove();svg.select("#circle").remove();svg.select("#stackbar").remove();svg.selectAll(".zoomi").attr("transform",d3.zoomIdentity);d3.select("#topg").attr("transform","translate("+translatetopg_val+",0)");zoom.scale(1);zoom.translate([0,0]);var b=chorddata[chrtonumber[a]];chrtorelchr=[];chrtorelchr_amount=[];for(var c=0;c<b.length;c++)0!==b[c]&&(chrtorelchr.push(numbertochr[c]),chrtorelchr_amount.push({chrname:numbertochr[c],
conn:b[c]}));chrtorelchr_amount.sort(function(a,b){return a.conn>b.conn?-1:1});blockdata_det=[];blockdata_det.push({i:2,j:4,name:a,ypos:heightgap/4+3*(onerectheight+heightgap)});var d=1;chrtorelchr_amount.forEach(function(a){blockdata_det.push({i:b_pos[d].i,j:b_pos[d].j,name:a.chrname,ypos:heightgap/4+(onerectheight+heightgap)*(b_pos[d].j-1)});d++});drawdata(a)},1)}
function drawblocks_det(){svg.select("#blocks")&&svg.select("#blocks").remove();svg.selectAll("#coltext").remove();svg.selectAll("#blockstext").remove();svgb=svg.append("g").attr("id","blocks");svgb.selectAll("rect").data(blockdata_det).enter().append("rect").attr("id",function(a){return a.name}).attr("width",rectwidth).attr("height",onerectheight).attr("fill","white").attr("fill-opacity",0).attr("stroke",function(a){return colorarr2[genetodna[a.name]]}).attr("stroke-opacity",1).attr("class","blocks").attr("transform",
transformblock_det).style("stroke-width",block_stroke_width).on("mouseover",function(a,b){d3.select(this).style("stroke","red")}).on("mouseout",function(a,b){d3.select(this).style("stroke",function(a){return colorarr2[genetodna[a.name]]})}).call(d3.behavior.drag().on("drag",dragged_det).on("dragstart",dragstart_det).on("dragend",dragend_det));svgb.append("g").attr("id","blockstext").selectAll("text").data(blockdata_det).enter().append("text").attr("transform",transformblocktext_det).attr("class",
"blocktext").attr("id",function(a){return a.name+"text"}).style("text-anchor","start").style("font-size","20px").style("font-weight","700").text(function(a){return a.name}).on("mouseover",function(a,b){d3.select(this).style("fill","red");d3.select(this).style("font-size","28px")}).on("mouseout",function(a,b){d3.select(this).style("fill","black");d3.select(this).style("font-size","20px")}).call(d3.behavior.drag().on("drag",dragged_dettext).on("dragstart",dragstart_dettext).on("dragend",dragend_dettext));
TotalCEdges_displayed=TotalEdges_displayed=TotalGenes_displayed=0;analytics()}function dragged_det(a){var b=d3.transform(this.getAttribute("transform")).translate;a=d3.event.dx+b[0];b=d3.event.dy+b[1];d3.select(this).attr("transform","translate("+a+","+b+")scale("+d3.transform(this.getAttribute("transform")).scale+")");svg.selectAll(".blocktext").attr("transform",transformblocktext_det)}function dragstart_det(a){d3.select(this).style("stroke-width","8px")}
function dragend_det(a,b){1.1>zoom.scale()&&(a.ypos=d3.transform(this.getAttribute("transform")).translate[1]);d3.select(this).style("stroke-width",block_stroke_width);text.attr("transform",transform_det);svg.selectAll(".links23").attr("d",function(a){return link_det(a)})}
function dragged_dettext(a){var b=d3.transform(this.getAttribute("transform")).translate,c=d3.transform(d3.select("#"+a.name)["0"]["0"].getAttribute("transform")).translate,d=d3.event.dx+b[0];b=d3.event.dy+b[1];d3.select(this).attr("transform","translate("+d+","+b+")scale("+d3.transform(this.getAttribute("transform")).scale+")");d=d3.event.dx+c[0];c=d3.event.dy+c[1];d3.select("#"+a.name).attr("transform","translate("+d+","+c+")scale("+d3.transform(d3.select("#"+a.name)["0"]["0"].getAttribute("transform")).scale+
")")}function dragstart_dettext(a){}function dragend_dettext(a,b){1.1>zoom.scale()&&(a.ypos=d3.transform(this.getAttribute("transform")).translate[1]);text.attr("transform",transform_det);svg.selectAll(".links23").attr("d",function(a){return link_det(a)})}
function transform_det(a){var b=svg.select("#"+a.Chr)["0"]["0"].attributes[8].value;t=b.slice(9,b.length);b=+t.slice(1,t.indexOf(","));var c=+t.slice(t.indexOf(",")+1,t.indexOf(")"));return"translate("+(b+1)+","+(c+genesinfo[a.Gene].returnpos*zoom.scale())+")"}
function transformblock_det(a){if(svg.select("#"+a.name)["0"]["0"].attributes[8]){var b=svg.select("#"+a.name)["0"]["0"].attributes[8].value;t=b.slice(9,b.length);b=+t.slice(1,t.indexOf(","));t.slice(t.indexOf(",")+1,t.indexOf(")"));return"translate("+b+","+y(a.ypos)+")scale("+[1,zoom.scale()]+")"}return"translate("+(onecolumnwidth/3+onecolumnwidth*(a.i-1))+","+y(heightgap/4+(onerectheight+heightgap)*(a.j-1))+")scale("+[1,zoom.scale()]+")"}
function transformblocktext_det(a){a=svg.select("#"+a.name)["0"]["0"].attributes[8].value;t=a.slice(9,a.length);a=+t.slice(1,t.indexOf(","));var b=+t.slice(t.indexOf(",")+1,t.indexOf(")"));return"translate("+(a+(rectwidth+5))+","+(b+onerectheight*zoom.scale()/2+10)+")scale(1,1)"}
function transforms_det(a){var b=svg.select("#"+a.Chr)["0"]["0"].attributes[8].value;t=b.slice(9,b.length);b=+t.slice(1,t.indexOf(","));var c=+t.slice(t.indexOf(",")+1,t.indexOf(")"));return a.Chr==exploredet_name?"translate("+(b+1)+","+(c+genesinfo[a.Gene].returnpos*zoom.scale())+")":"translate("+(b+1)+","+(c+1*genesinfo[a.Gene].returnpos)+")"}
function transformblocks_det(a){return a.name==exploredet_name?"translate("+(onecolumnwidth/3+onecolumnwidth*(a.i-1))+","+y(heightgap/4+(onerectheight+heightgap)*(a.j-1))+")scale("+[1,zoom.scale()]+")":"translate("+(onecolumnwidth/3+onecolumnwidth*(a.i-1))+","+(heightgap/4+(onerectheight+heightgap)*(a.j-1))+")scale(1,1)"}
function transformblocktexts_det(a){return a.name==exploredet_name?"translate("+(onecolumnwidth/3+onecolumnwidth*(a.i-1)+(rectwidth+5))+","+y(heightgap/4+(onerectheight+heightgap)*(a.j-1)+onerectheight/2+10)+")scale(1,1)":"translate("+(onecolumnwidth/3+onecolumnwidth*(a.i-1)+(rectwidth+5))+","+(heightgap/4+(onerectheight+heightgap)*(a.j-1)+onerectheight/2+10)+")scale(1,1)"}
function drawdata(a){spinner.spin(document.getElementById("vis"));setTimeout(function(){svg.select("#edgesg")&&svg.select("#edgesg").remove();svg.select("#genesg")&&svg.select("#genesg").remove();svg.selectAll(".zoomi").attr("transform",d3.zoomIdentity);svg.attr("transform",d3.zoomIdentity);d3.select("#topg").attr("transform","translate("+translatetopg_val+",0)");zoom.scale(1);zoom.translate([0,0]);drawblocks_det();drawfiltergenes_det(genesdata,a);drawfilteredges_det(edgesdata,a);spinner.stop()},
1)}
function drawfiltergenes_det(a,b){chrnames.indexOf(genetodna[b]);var c=chrtogenesneighbor[b];c=c.concat(chrtogenes[b]);for(var d=[],e=0;e<c.length;e++)d.push({Chr:genesinfo[c[e]].Chr,Gene:c[e],Start:genesinfo[c[e]].Start,End:genesinfo[c[e]].End});TotalGenes_displayed=d.length;text=svg.append("g").attr("id","genesg").selectAll("rect").data(d).enter().append("rect").attr("id",function(a){return a.Gene.replace(".","_")}).attr("transform",transform_det).attr("width",rectwidth-2).attr("height",function(a){return genesinfo[a.Gene].returnposheight*zoom.scale()}).attr("fill",
function(a){return genesinfo[a.Gene].color}).attr("fill-opacity",gene_opcaity).attr("class","nodes").on("mouseover",nodemouseover2).on("mouseout",nodemouseout2).on("click",function(a,b){var c="",d=new XMLHttpRequest;d.onreadystatechange=function(){if(200==d.status&&4==d.readyState){c=d.responseText;var b=window.open("","_blank","left=0,top=0,width=700,height=700");b.document.write("<title>Gene Detail</title> <center><b><h2>"+a.Gene+"</b></h2></center>  <br /><br /><p>"+c+"</p>");b.document.close()}};
d.open("GET","samplegene.txt",!0);d.send()});text2=text.append("svg:title").text(function(a){return a.Gene+"\n"})}
function drawfilteredges_det(a,b){for(var c=chrtogenes[b],d=[],e=0;e<c.length;e++){var f=genesneighbours[c[e]],h=c[e];if(f)for(var g=0;g<f.length;g++){var l=f[g];chrnames.indexOf(genesinfo[h].species);chrnames.indexOf(genesinfo[l].species);d.push({source:h,target:l})}}var m=0;svg.append("g").attr("id","edgesg").selectAll("links23").data(d).enter().append("path").attr("class","links23").attr("d",function(a){return link_det(a)}).style("stroke-width",function(a){return Math.abs(genesinfo[a.target].ypos-
genesinfo[a.source].ypos)>crossedge_threshold?(m++,highlightcrossedges?stroke_width_cross_highlight:stroke_width_cross):stroke_width_straight}).style("stroke",function(a,b){return genesinfo[a.target].color}).style("fill","transparent").style("opacity",function(a){return Math.abs(genesinfo[a.target].ypos-genesinfo[a.source].ypos)>crossedge_threshold?highlightcrossedges?stroke_opacity_cross_highlight:stroke_opacity_cross:stroke_opacity_straight}).on("mouseover",edgemouseover).on("mouseout",edgemouseout).attr("id",
function(a){return a.source.replace(".","_")+""+a.target.replace(".","_")}).append("svg:title").text(function(a){return a.source+" "+a.target});svg.select("#edgesg").moveToBack();TotalEdges_displayed=d.length;TotalCEdges_displayed=m;analytics();showcontrols()}
function link_det(a){if(svg.select("#"+genesinfo[a.source].Chr)["0"]["0"]){var b=svg.select("#"+genesinfo[a.source].Chr)["0"]["0"].attributes[8].value;if(svg.select("#"+genesinfo[a.target].Chr)["0"]["0"]){var c=svg.select("#"+genesinfo[a.target].Chr)["0"]["0"].attributes[8].value;b=b.slice(9,b.length);var d=+b.slice(1,b.indexOf(","));c=c.slice(9,c.length);var e=+c.slice(1,c.indexOf(","));b=svg.select("#"+a.source.replace(".","_"))["0"]["0"].transform.animVal["0"].matrix.f;c=svg.select("#"+a.target.replace(".",
"_"))["0"]["0"].transform.animVal["0"].matrix.f;var f=svg.select("#"+a.source.replace(".","_"))["0"]["0"].transform.animVal["0"].matrix.e,h=svg.select("#"+a.target.replace(".","_"))["0"]["0"].transform.animVal["0"].matrix.e;if(!showviewportonlyedges||!(0>b||b>height||0>c||c>height)){if(d<e)return a=+f+rectwidth-1,d=+h-1,f=d3.interpolateNumber(a,d),e=f(curvature),f=f(1-curvature),"M"+a+","+b+"C"+e+","+b+" "+f+","+c+" "+d+","+c;if(e<d)return a=+f-1,d=+h+rectwidth-1,f=d3.interpolateNumber(a,d),e=f(curvature),
f=f(1-curvature),"M"+a+","+b+"C"+e+","+b+" "+f+","+c+" "+d+","+c}}}}var blocks_connections=1;
function showcontrols(){hide_details_controls();var a=width-onecolumnwidth/3-Math.abs(translatetopg_val/3),b=onecolumnwidth/3+Math.abs(translatetopg_val)+5,c=svg.append("g").attr("id","controls").attr("transform","translate("+a+","+heightgap/4+")");c.append("rect").attr("width",b).attr("height",240).attr("fill","white").attr("fill-opacity",0).attr("stroke","#d43f3a").attr("stroke-width","2px").attr("stroke-opacity",1);c.append("text").attr("x",b/2).attr("y",0).attr("dy","1.2em").style("text-anchor",
"middle").attr("font-size","24px").attr("font-weight","bold").attr("fill","#d43f3a").text("Filters");var d=c.append("text").attr("x",b/2).attr("y",50).attr("dy","1.2em").style("text-anchor","middle").attr("font-size","12px").attr("font-weight","bold").attr("fill","black").text("Blocks with atleast 1 connections"),e=new simpleSlider;blocks_connections=1;var f=d3.scale.linear().domain([1,500]).range([1E-5,1]);e.width(b-20).x(10).y(80).value(f(1)).event(function(){d.text("Blocks with atleast "+f.invert(e.value()).toFixed(0)+
" connections");blocks_connections=f.invert(e.value()).toFixed(0)});e.event2(function(){updateview_removeselblocks()});c.call(e);$("#labeld")["0"].style.display="block";$("#labeld")["0"].style.transform="translate("+(a-Math.abs(translatetopg_val)/1.5)+"px,110px)";$("#detail_crossedges").prop("checked")&&$("#detail_crossedges").prop("checked",!1).change();$("#labeld2")["0"].style.display="block";$("#labeld2")["0"].style.transform="translate("+(a-Math.abs(translatetopg_val)/1.5)+"px,150px)";$("#removechr")["0"].style.display=
"block";$("#removechr")["0"].style.transform="translate("+(a-Math.abs(translatetopg_val)/1.5)+"px,200px)";removechrfunc();$("#detail_crossedges").change(function(){updateview_removeselblocks()})}function layoutchange(a){alert("This feature will be available later")}var details_selcb=[],con=0;
function removechrfunc(){$("#dropblocks").remove();$("<ul />",{type:"ul",id:"dropblocks","class":"dropdown-menu checkbox-menu23 allow-focus",style:"min-width:205px ; text-align:left;"}).appendTo($("#removechr"));details_selcb=[];con++;for(var a=0;a<chrtorelchr.length;a++)addCheckbox_explore(chrtorelchr[a]);$(".checkbox-menu23").on("change","input[type='checkbox']",function(){$(this).closest("li")["0"].style.backgroundColor="#5aa8f6";$(this).prop("checked")?($("#removechr1").html('Remove Selected Blocks:   <span class="caret"></span>'),
details_selcb.includes($(this).val())||details_selcb.push($(this).val())):($("#removechr1").html('Remove Selected Blocks:   <span class="caret"></span>'),$(this).closest("li")["0"].style.backgroundColor="transparent",-1!==details_selcb.indexOf($(this).val())&&details_selcb.splice(details_selcb.indexOf($(this).val()),1));updateview_removeselblocks()})}
function addCheckbox_explore(a){var b=$("#dropblocks"),c=b.find("input").length+1,d=colorarr2[genetodna[a]];b=$("<li />",{id:con+"li"+c,"class":"lisforul",style:"width:205px ; text-align:left;"}).appendTo(b);$("<input />",{type:"checkbox",id:con+"cbe"+c,value:a,style:"display: inline-block; margin-left:20px;vertical-align: sub; width: 15px;height: 15px;"}).appendTo(b);$("<label />",{"for":con+"cbe"+c,text:a,"class":"check",style:"display: inline-block;padding: 0px 0px; font-weight: bold;color:"+d+
";min-width: 125px;margin-left: 5px; margin-bottom: 0px;"}).appendTo(b)}function hide_details_controls(){$("#labeld")["0"].style.display="none";$("#labeld2")["0"].style.display="none";$("#removechr")["0"].style.display="none";svg.select("#controls")&&svg.select("#controls").remove()}
function updateview_removeselblocks(){setTimeout(function(){svg.select("#edgesg").remove();svg.select("#genesg").remove();svg.select("#circle").remove();svg.select("#stackbar").remove();svg.selectAll(".zoomi").attr("transform",d3.zoomIdentity);d3.select("#topg").attr("transform","translate("+translatetopg_val+",0)");zoom.scale(1);zoom.translate([0,0]);var a=chorddata[chrtonumber[exploredet_name]];chrtorelchr=[];chrtorelchr_amount=[];for(var b=0;b<a.length;b++)0===a[b]||a[b]<blocks_connections||(chrtorelchr.push(numbertochr[b]),
chrtorelchr_amount.push({chrname:numbertochr[b],conn:a[b]}));chrtorelchr_amount.sort(function(a,b){return a.conn>b.conn?-1:1});blockdata_det=[];blockdata_det.push({i:2,j:4,name:exploredet_name,ypos:heightgap/4+3*(onerectheight+heightgap)});var c=1;chrtorelchr_amount.forEach(function(a){details_selcb.includes(a.chrname)||(blockdata_det.push({i:b_pos[c].i,j:b_pos[c].j,name:a.chrname,ypos:heightgap/4+(onerectheight+heightgap)*(b_pos[c].j-1)}),c++)});drawdata_rem(exploredet_name);a=$(".lisforul").closest("li");
for(b=0;b<a.length;b++)chrtorelchr.includes($("#"+a[b].id)["0"].innerText)?$("#"+a[b].id)["0"].childNodes["0"].checked?a[b].style.backgroundColor="#5aa8f6":a[b].style.backgroundColor="transparent":a[b].style.backgroundColor="#9e9e9e5e"},1)}
function nodemouseover2(a){if(showmousehighlights){d3.select(this).style("fill-opacity","1");d3.select(this).style("stroke",genehighlightcolor);var b=genesneighbours[a.Gene];if(b&&"undefined"!==typeof genesneighbours[a.Gene]){b=b.filter(function(a){return 0===a||a});for(var c=0;c<b.length;c++){d3.select("#"+b[c].replace(".","_")).style("fill-opacity","1");d3.select("#"+b[c].replace(".","_")).style("stroke",genehighlightcolor);var d=d3.select(this).attr("id").replace(".","_")+""+b[c].replace(".","_"),
e=b[c].replace(".","_")+""+d3.select(this).attr("id").replace(".","_");d3.select("#"+d)["0"]["0"]?(d3.select("#"+d).style("stroke-width",highlighted_edge_stroke_width),d3.select("#"+d).style("stroke",edgehighlightcolor),d3.select("#"+d).style("opacity","1")):d3.select("#"+e)["0"]["0"]&&(d3.select("#"+e).style("stroke-width",highlighted_edge_stroke_width),d3.select("#"+e).style("stroke",edgehighlightcolor),d3.select("#"+e).style("opacity","1"))}}inexploredet&&b&&0<b.length&&showegonetwork(a,b)}}
function nodemouseout2(a){if(showmousehighlights){d3.select(this).style("fill-opacity",gene_opcaity);d3.select(this).style("stroke","none");var b=genesneighbours[a.Gene];if(b&&"undefined"!==typeof genesneighbours[a.Gene])for(b=b.filter(function(a){return 0===a||a}),a=0;a<b.length;a++){d3.select("#"+b[a].replace(".","_")).style("fill-opacity",gene_opcaity);d3.select("#"+b[a].replace(".","_")).style("stroke","none");var c=d3.select(this).attr("id").replace(".","_")+""+b[a].replace(".","_"),d=b[a].replace(".",
"_")+""+d3.select(this).attr("id").replace(".","_");d3.select("#"+c)["0"]["0"]?(d3.select("#"+c).style("stroke-width",Math.abs(genesinfo[b[a]].ypos-genesinfo[d3.select(this).attr("id").replace("_",".")].ypos)>crossedge_threshold?stroke_width_cross:stroke_width_straight),svg.select("#"+b[a].replace(".","_"))["0"]["0"]&&d3.select("#"+c).style("stroke",svg.select("#"+b[a].replace(".","_"))["0"]["0"].attributes[4].value),d3.select("#"+c).style("opacity",Math.abs(genesinfo[b[a]].ypos-genesinfo[d3.select(this).attr("id").replace("_",
".")].ypos)>crossedge_threshold?stroke_opacity_cross:stroke_opacity_straight)):d3.select("#"+d)["0"]["0"]&&(d3.select("#"+d).style("stroke-width",Math.abs(genesinfo[b[a]].ypos-genesinfo[d3.select(this).attr("id").replace("_",".")].ypos)>crossedge_threshold?stroke_width_cross:stroke_width_straight),svg.select("#"+b[a].replace(".","_"))["0"]["0"]&&d3.select("#"+d).style("stroke",svg.select("#"+d3.select(this).attr("id").replace(".","_"))["0"]["0"].attributes[4].value),d3.select("#"+d).style("opacity",
Math.abs(genesinfo[b[a]].ypos-genesinfo[d3.select(this).attr("id").replace("_",".")].ypos)>crossedge_threshold?stroke_opacity_cross:stroke_opacity_straight))}inexploredet&&svg.select("#egonetwork")&&svg.select("#egonetwork").remove()}}
function showegonetwork(a,b){svg.select("#egonetwork")&&svg.select("#egonetwork").remove();var c=svg.append("g").attr("id","egonetwork").attr("transform","translate("+(3*onecolumnwidth-onecolumnwidth/3.5)+","+(height-310)+")");c.append("rect").attr("x",-4).attr("y",0).attr("width",onecolumnwidth).attr("height",300).attr("fill","white").attr("fill-opacity",0).attr("stroke","#d43f3a").attr("stroke-width","2px").attr("stroke-opacity",1);c.append("text").attr("x",onecolumnwidth/2).attr("y",0).attr("dy",
"1.2em").style("text-anchor","middle").attr("font-size","24px").attr("font-weight","bold").attr("fill","#d43f3a").text("Gene Network");var d={0:{x:25,y:50},1:{x:onecolumnwidth-onecolumnwidth/4-25,y:50},2:{x:25,y:250},3:{x:onecolumnwidth-onecolumnwidth/4-25,y:250},10:{x:onecolumnwidth/2-onecolumnwidth/8,y:135}};var e={0:{x:25,y:50},1:{x:onecolumnwidth-onecolumnwidth/4-25,y:50},2:{x:onecolumnwidth/2-onecolumnwidth/8,y:250},10:{x:onecolumnwidth/2-onecolumnwidth/8,y:135}},f={0:{x:25,y:135},1:{x:onecolumnwidth-
onecolumnwidth/4-25,y:135},10:{x:onecolumnwidth/2-onecolumnwidth/8,y:135}},h={10:{x:25,y:135},0:{x:onecolumnwidth-onecolumnwidth/4-25,y:135}},g={0:{x1:25+onecolumnwidth/8,y1:80,x2:onecolumnwidth/2,y2:135},1:{x1:onecolumnwidth-onecolumnwidth/8-25,y1:80,x2:onecolumnwidth/2,y2:135},2:{x1:onecolumnwidth/2,y1:250,x2:onecolumnwidth/2,y2:165}},l={0:{x1:25+onecolumnwidth/4,y1:150,x2:onecolumnwidth/2-onecolumnwidth/8,y2:150},1:{x1:onecolumnwidth-onecolumnwidth/4-25,y1:150,x2:onecolumnwidth/2+onecolumnwidth/
8,y2:150}},m={0:{x1:onecolumnwidth-onecolumnwidth/4-25,y1:150,x2:25+onecolumnwidth/4,y2:150}};if(4!=b.length)if(3==b.length){d=e;var k=g}else 2==b.length?(d=f,k=l):(d=h,k=m);c.append("rect").attr("x",d["10"].x).attr("y",d["10"].y).attr("rx",6).attr("ry",6).attr("width",onecolumnwidth/4).attr("height",30).attr("fill","white").attr("fill-opacity",0).attr("stroke",colorarr2[genetodna[a.Chr]]).attr("stroke-width","2px").attr("stroke-opacity",1);c.append("text").attr("x",d["10"].x+onecolumnwidth/8).attr("y",
d["10"].y+7).attr("dy","1.2em").style("text-anchor","middle").attr("font-size","11px").attr("fill","black").text(a.Gene);for(g=0;g<b.length;g++)c.append("rect").attr("x",d[g].x).attr("y",d[g].y).attr("rx",6).attr("ry",6).attr("width",onecolumnwidth/4).attr("height",30).attr("fill","white").attr("fill-opacity",0).attr("stroke",colorarr2[genetodna[genesinfo[b[g].replace("_",".")].Chr]]).attr("stroke-width","2px").attr("stroke-opacity",1),c.append("text").attr("x",d[g].x+onecolumnwidth/8).attr("y",d[g].y+
7).attr("dy","1.2em").style("text-anchor","middle").attr("font-size","11px").attr("fill","black").text(b[g]),c.append("line").attr("x1",k[g].x1).attr("y1",k[g].y1).attr("x2",k[g].x2).attr("y2",k[g].y2).attr("stroke-width",2).attr("stroke",colorarr2[genetodna[genesinfo[b[g].replace("_",".")].Chr]])};