var timer=[],delay=200,svgb,prevent=!1,bw=d3.scale.linear().domain([0,100,200,500,1E3,1500,2E3,4600]).range([1,1.1,1.5,2,2.5,3,4,6]);
function drawblocks(){svg.select("#blocks")&&svg.select("#blocks").remove();svg.selectAll("#coltext").remove();svg.selectAll("#blockstext").remove();svgb=svg.append("g").attr("id","blocks");svgb.selectAll("rect").data(blockdata).enter().append("rect").attr("id",function(a){return rectmap[+(""+a.i+a.j)]}).attr("width",rectwidth).attr("height",onerectheight).attr("fill","white").attr("fill-opacity",0).attr("stroke",function(a){return colorarr[a.i]}).attr("stroke-opacity",1).attr("class","blocks").attr("transform",
transformblock).on("click",function(a,b){var c=d3.select(this)["0"]["0"].id;timer[""+a.i+a.j]=setTimeout(function(){prevent||chrclicked(c);prevent=!1},delay)}).on("dblclick",function(a){var b=d3.select(this)["0"]["0"].id;clearTimeout(timer[""+a.i+a.j]);prevent=!0;chrdblclicked(b)}).style("stroke-width",function(a){return bw(crossedgesdata_sum[a.name])});svgb.append("g").attr("id","blockstext").selectAll("text").data(blockdata).enter().append("text").attr("transform",transformblocktext).attr("class",
"blocktext").attr("id",function(a){return rectmap[+(""+a.i+a.j)]+"text"}).style("text-anchor","start").style("font-size","20px").style("font-weight","700").on("mouseover",function(a,b){d3.select(this).style("fill",function(a){return colorarr2[genetodna[a.name]]});for(var c=chorddata_crossedges[chrtonumber[a.name]],d={},e=0;e<c.length;e++)0!==c[e]&&(d[numbertochr[e]]=c[e]);drawWordCloud(d,d3.transform(this.getAttribute("transform")).translate[0],d3.transform(this.getAttribute("transform")).translate[1])}).on("mouseout",
function(a,b){d3.select(this).style("fill","black");svg.select("#wordcloud")&&svg.select("#wordcloud").remove()}).text(function(a){return rectmap[+(""+a.i+a.j)]});svgb.append("g").attr("id","coltext").selectAll("text").data(chrnames).enter().append("text").attr("x",function(a,b){return onecolumnwidth/3+onecolumnwidth*b+rectwidth/2}).attr("y",function(a,b){return heightgap/4+(onerectheight+heightgap)*(noofchr-1)+onerectheight+20}).attr("id",function(a){return a}).call(d3.behavior.drag().on("drag",
dragged).on("dragstart",dragstart).on("dragend",dragend)).style("text-anchor","middle").style("font-size","22px").style("font-weight","800").attr("fill",function(a,b){return colorarr[b+1]}).text(function(a){return a});TotalCEdges_displayed=TotalEdges_displayed=TotalGenes_displayed=0;analytics()}function dragged(a){clickednodes_check&&dragging&&d3.select(this).attr("x",this.x.animVal["0"].value+d3.event.dx)}
function dragstart(a){clickednodes_check&&dragging&&d3.select(this).style("font-size","32px");semanticzoomone&&(sel_chr=a,svg.selectAll("#coltext").selectAll("text").attr("fill",function(a,c){return a==sel_chr?"black":colorarr[c+1]}),zoom.scale(1),zoom.translate([0,0]))}
function dragend(a,b){if(clickednodes_check&&dragging){d3.select(this).style("font-size","24px");var c=chrnames.indexOf(this.id),d=null,e=null;4>c+1&&(d=xposarr[c]);0<=c-1&&(e=xposarr[c-1]);d&&this.x.animVal["0"].value>d?swap(chrnames,c,c+1):e&&this.x.animVal["0"].value<e&&swap(chrnames,c-1,c);clickednodesedges()}}
function swap(a,b,c){var d=a[b];a[b]=a[c];a[c]=d;for(a=1;a<=noofcolumns;a++)for(d=1;d<=noofchr;d++){var e=""+a+d,f;"Barley"==chrnames[a-1]?f="hv"+d+"H":"WheatA"==chrnames[a-1]?f="ta"+d+"A":"WheatB"==chrnames[a-1]?f="ta"+d+"B":"WheatD"==chrnames[a-1]&&(f="ta"+d+"D");rectmap[+e]=f}f=colorarr[b+1];colorarr[b+1]=colorarr[c+1];colorarr[c+1]=f;swappingcheck_alledge=!0}var sc=d3.scale.linear();function returnpos(a,b,c){return sc.domain([1,chrlengths[a]]).range([1,onerectheight*c])(b)}
function transform(a){var b=svg.select("#"+a.Chr)["0"]["0"].attributes[8].value;t=b.slice(9,b.length);b=+t.slice(1,t.indexOf(","));var c=+t.slice(t.indexOf(",")+1,t.indexOf(")"));return doubleclickedrect&&a.Chr==nodename?"translate("+(b+1)+","+(c+returnpos_onebig(a.Chr,a.Start,zoom.scale()))+")":"translate("+(b+1)+","+(c+genesinfo[a.Gene].returnpos*zoom.scale())+")"}
function transformblock(a){return doubleclickedrect&&rectmap[+(""+a.i+a.j)]==nodename?"translate("+(onecolumnwidth/3+onecolumnwidth*(a.i-1))+","+y(heightgap/4+0*(onerectheight+heightgap))+")scale("+[1,zoom.scale()]+")":"translate("+(onecolumnwidth/3+onecolumnwidth*(a.i-1))+","+y(heightgap/4+(onerectheight+heightgap)*(a.j-1))+")scale("+[1,zoom.scale()]+")"}
function transformblocktext(a){return doubleclickedrect&&rectmap[+(""+a.i+a.j)]==nodename?"translate("+(onecolumnwidth/3+onecolumnwidth*(a.i-1)+(rectwidth+5))+","+y(heightgap/4+3*(onerectheight+heightgap)+onerectheight/2+10)+")scale(1,1)":"translate("+(onecolumnwidth/3+onecolumnwidth*(a.i-1)+(rectwidth+5))+","+y(heightgap/4+(onerectheight+heightgap)*(a.j-1)+onerectheight/2+10)+")scale(1,1)"}
function transforms(a){var b=svg.select("#"+a.Chr)["0"]["0"].attributes[8].value;t=b.slice(9,b.length);b=+t.slice(1,t.indexOf(","));var c=+t.slice(t.indexOf(",")+1,t.indexOf(")"));return doubleclickedrect&&a.Chr==nodename?genetodna[a.Chr]==sel_chr?"translate("+(b+1)+","+(c+returnpos_onebig(a.Chr,a.Start,zoom.scale()))+")":"translate("+(b+1)+","+(c+returnpos_onebig(a.Chr,a.Start,1))+")":genetodna[a.Chr]==sel_chr?"translate("+(b+1)+","+(c+genesinfo[a.Gene].returnpos*zoom.scale())+")":"translate("+(b+
1)+","+(c+1*genesinfo[a.Gene].returnpos)+")"}
function transformblocks(a){return doubleclickedrect&&rectmap[+(""+a.i+a.j)]==nodename?genetodna[rectmap[+(""+a.i+a.j)]]==sel_chr?"translate("+(onecolumnwidth/3+onecolumnwidth*(a.i-1))+","+y(heightgap/4+0*(onerectheight+heightgap))+")scale("+[1,zoom.scale()]+")":"translate("+(onecolumnwidth/3+onecolumnwidth*(a.i-1))+","+(heightgap/4+0*(onerectheight+heightgap))+")scale(1,1)":genetodna[rectmap[+(""+a.i+a.j)]]==sel_chr?"translate("+(onecolumnwidth/3+onecolumnwidth*(a.i-1))+","+y(heightgap/4+(onerectheight+
heightgap)*(a.j-1))+")scale("+[1,zoom.scale()]+")":"translate("+(onecolumnwidth/3+onecolumnwidth*(a.i-1))+","+(heightgap/4+(onerectheight+heightgap)*(a.j-1))+")scale(1,1)"}
function transformblocktexts(a){return doubleclickedrect&&rectmap[+(""+a.i+a.j)]==nodename?genetodna[rectmap[+(""+a.i+a.j)]]==sel_chr?"translate("+(onecolumnwidth/3+onecolumnwidth*(a.i-1)+(rectwidth+5))+","+y(heightgap/4+3*(onerectheight+heightgap)+onerectheight/2+10)+")scale(1,1)":"translate("+(onecolumnwidth/3+onecolumnwidth*(a.i-1)+(rectwidth+5))+","+(heightgap/4+3*(onerectheight+heightgap)+onerectheight/2+10)+")scale(1,1)":genetodna[rectmap[+(""+a.i+a.j)]]==sel_chr?"translate("+(onecolumnwidth/
3+onecolumnwidth*(a.i-1)+(rectwidth+5))+","+y(heightgap/4+(onerectheight+heightgap)*(a.j-1)+onerectheight/2+10)+")scale(1,1)":"translate("+(onecolumnwidth/3+onecolumnwidth*(a.i-1)+(rectwidth+5))+","+(heightgap/4+(onerectheight+heightgap)*(a.j-1)+onerectheight/2+10)+")scale(1,1)"}var text;
function drawgenes(a){var b=(new Date).getTime(),c=[];a.forEach(function(a){if(genesneighbours[a.Gene]){for(var b=!1,d=0;d<genesneighbours[a.Gene].length;d++)if(1==Math.abs(genesinfo[a.Gene].species_col_index-genesinfo[genesneighbours[a.Gene][d]].species_col_index)){b=!0;break}b&&c.push({Chr:a.Chr,Gene:a.Gene,Start:a.Start,End:a.End})}});TotalGenes_displayed=c.length;text=svg.append("g").attr("id","genesg").selectAll("rect").data(c).enter().append("rect").attr("id",function(a){return a.Gene.replace(".",
"_")}).attr("transform",transform).attr("width",rectwidth-2).attr("height",function(a){return genesinfo[a.Gene].returnposheight}).attr("fill",function(a){return genesinfo[a.Gene].color}).attr("fill-opacity",gene_opcaity_allgenes);text2=text.append("svg:title").text(function(a){return a.Gene+"\n"+sample_gene});a=(new Date).getTime();console.log(a+" allgenes  "+(a-b)/1E3)}
function drawfiltergenes(a,b){var c=chrnames.indexOf(genetodna[b]),d=0<c?chrnames[c-1]:null;c=c<chrnames.length-1?chrnames[c+1]:null;var e=chrtogenesneighbor[b];e=e.concat(chrtogenes[b]);for(var f=[],g=0;g<e.length;g++)genetodna[genesinfo[e[g]].Chr]!=d&&genetodna[genesinfo[e[g]].Chr]!=c&&genesinfo[e[g]].Chr!=b||f.push({Chr:genesinfo[e[g]].Chr,Gene:e[g],Start:genesinfo[e[g]].Start,End:genesinfo[e[g]].End});TotalGenes_displayed=f.length;text=svg.append("g").attr("id","genesg").selectAll("rect").data(f).enter().append("rect").attr("id",
function(a){return a.Gene.replace(".","_")}).attr("transform",transform).attr("width",rectwidth-2).attr("height",function(a){return genesinfo[a.Gene].returnposheight*zoom.scale()}).attr("fill",function(a){return genesinfo[a.Gene].color}).attr("fill-opacity",gene_opcaity).attr("class","nodes").on("mouseover",nodemouseover).on("mouseout",nodemouseout).on("click",function(a,b){var c="",d=new XMLHttpRequest;d.onreadystatechange=function(){if(200==d.status&&4==d.readyState){c=d.responseText;var b=window.open("",
"_blank","left=0,top=0,width=700,height=700");b.document.write("<title>Gene Detail</title> <center><b><h2>"+a.Gene+"</b></h2></center>  <br /><br /><p>"+c+"</p>");b.document.close()}};d.open("GET","samplegene.txt",!0);d.send()});text2=text.append("svg:title").text(function(a){return a.Gene+"\n"+sample_gene})}
function nodemouseover(a){if(showmousehighlights&&(d3.select(this).style("fill-opacity","1"),d3.select(this).style("stroke",genehighlightcolor),a=genesneighbours[d3.select(this).attr("id").replace("_",".")]))for(var b=0;b<a.length;b++){d3.select("#"+a[b].replace(".","_")).style("fill-opacity","1");d3.select("#"+a[b].replace(".","_")).style("stroke",genehighlightcolor);var c=d3.select(this).attr("id").replace(".","_")+""+a[b].replace(".","_"),d=a[b].replace(".","_")+""+d3.select(this).attr("id").replace(".",
"_");d3.select("#"+c)["0"]["0"]?(d3.select("#"+c).style("stroke-width",highlighted_edge_stroke_width),d3.select("#"+c).style("stroke",edgehighlightcolor),d3.select("#"+c).style("opacity","1")):d3.select("#"+d)["0"]["0"]&&(d3.select("#"+d).style("stroke-width",highlighted_edge_stroke_width),d3.select("#"+d).style("stroke",edgehighlightcolor),d3.select("#"+d).style("opacity","1"))}}
function nodemouseout(a){if(showmousehighlights&&(d3.select(this).style("fill-opacity",gene_opcaity),d3.select(this).style("stroke","none"),a=genesneighbours[d3.select(this).attr("id").replace("_",".")]))for(var b=0;b<a.length;b++){d3.select("#"+a[b].replace(".","_")).style("fill-opacity",gene_opcaity);d3.select("#"+a[b].replace(".","_")).style("stroke","none");var c=d3.select(this).attr("id").replace(".","_")+""+a[b].replace(".","_"),d=a[b].replace(".","_")+""+d3.select(this).attr("id").replace(".",
"_");d3.select("#"+c)["0"]["0"]?(d3.select("#"+c).style("stroke-width",Math.abs(genesinfo[a[b]].ypos-genesinfo[d3.select(this).attr("id").replace("_",".")].ypos)>crossedge_threshold?stroke_width_cross:stroke_width_straight),svg.select("#"+a[b].replace(".","_"))["0"]["0"]&&d3.select("#"+c).style("stroke",svg.select("#"+a[b].replace(".","_"))["0"]["0"].attributes[4].value),d3.select("#"+c).style("opacity",Math.abs(genesinfo[a[b]].ypos-genesinfo[d3.select(this).attr("id").replace("_",".")].ypos)>crossedge_threshold?
stroke_opacity_cross:stroke_opacity_straight)):d3.select("#"+d)["0"]["0"]&&(d3.select("#"+d).style("stroke-width",Math.abs(genesinfo[a[b]].ypos-genesinfo[d3.select(this).attr("id").replace("_",".")].ypos)>crossedge_threshold?stroke_width_cross:stroke_width_straight),svg.select("#"+a[b].replace(".","_"))["0"]["0"]&&d3.select("#"+d).style("stroke",svg.select("#"+d3.select(this).attr("id").replace(".","_"))["0"]["0"].attributes[4].value),d3.select("#"+d).style("opacity",Math.abs(genesinfo[a[b]].ypos-
genesinfo[d3.select(this).attr("id").replace("_",".")].ypos)>crossedge_threshold?stroke_opacity_cross:stroke_opacity_straight))}}var nodename;
function chrclicked(a){if(clickednodes_check){var b=(new Date).getTime();spinner.spin(document.getElementById("vis"));nodename=a;check_doubleclickrect=doubleclickedrect=!1;sel_chr="";setTimeout(function(){svg.select("#edgesg")&&svg.select("#edgesg").remove();svg.select("#genesg")&&svg.select("#genesg").remove();svg.selectAll(".zoomi").attr("transform",d3.zoomIdentity);svg.attr("transform",d3.zoomIdentity);d3.select("#topg").attr("transform","translate("+translatetopg_val+",0)");zoom.scale(1);zoom.translate([0,
0]);drawblocks();d3.select("#"+nodename).style("stroke","black");drawfiltergenes(genesdata,nodename);drawfilteredges(edgesdata,nodename);spinner.stop();var a=(new Date).getTime();console.log(a+" chr clicked  "+(a-b)/1E3)},1)}}
function chrdblclicked(a){if(clickednodes_check){var b=(new Date).getTime();spinner.spin(document.getElementById("vis"));nodename=a;check_doubleclickrect=doubleclickedrect=!0;sel_chr="";setTimeout(function(){svg.select("#edgesg")&&svg.select("#edgesg").remove();svg.select("#genesg")&&svg.select("#genesg").remove();svg.selectAll(".zoomi").attr("transform",d3.zoomIdentity);svg.attr("transform",d3.zoomIdentity);d3.select("#topg").attr("transform","translate("+translatetopg_val+",0)");zoom.scale(1);zoom.translate([0,
0]);drawblocks_onebig(a);d3.select("#"+nodename).style("stroke","black");drawfiltergenes_onebig(genesdata,nodename);drawfilteredges(edgesdata,nodename);spinner.stop();var c=(new Date).getTime();console.log(c+" chr dblclicked  "+(c-b)/1E3)},1)}}
function drawgenes_cross(a){TotalGenes_displayed=a.length;text=svg.append("g").attr("id","genesg").selectAll("rect").data(a).enter().append("rect").attr("id",function(a){return a.Gene.replace(".","_")}).attr("transform",transform).attr("width",rectwidth-2).attr("height",function(a){return genesinfo[a.Gene].returnposheight}).attr("fill",function(a){return genesinfo[a.Gene].color}).attr("fill-opacity",gene_opcaity).on("mouseover",nodemouseover).on("mouseout",nodemouseout).attr("class","nodes");text2=
text.append("svg:title").text(function(a){return a.Gene+"\n"+sample_gene})}
function analytics(){svg.select("#analyticsg")&&svg.select("#analyticsg").remove();var a=svg.append("g").attr("id","analyticsg").attr("transform","translate("+(width-Math.abs(3*translatetopg_val)+20)+","+(height-150)+")");a.append("rect").attr("x",-4).attr("y",0).attr("width",Math.abs(3*translatetopg_val)+20).attr("height",140).attr("fill","white").attr("fill-opacity",0).attr("stroke","#d43f3a").attr("stroke-width","2px").attr("stroke-opacity",1);a.append("text").attr("x",(Math.abs(3*translatetopg_val)+
20)/2).attr("y",0).attr("dy","1.2em").style("text-anchor","middle").attr("font-size","24px").attr("font-weight","bold").attr("fill","#d43f3a").text("Analytics");a.append("text").attr("x",0).attr("y",35).attr("dy","1.2em").style("text-anchor","start").attr("font-size","16px").attr("font-weight","bold").attr("fill","black").text("Blocks:"+(1==inexploredet?svg.select("#blocks")["0"]["0"].childNodes.length-1:svg.select("#blocks")["0"]["0"].childNodes.length-2));a.append("text").attr("x",0).attr("y",60).attr("dy",
"1.2em").style("text-anchor","start").attr("font-size","16px").attr("font-weight","bold").attr("fill","black").text("Genes:"+TotalGenes_displayed);a.append("text").attr("x",0).attr("y",85).attr("dy","1.2em").style("text-anchor","start").attr("font-size","16px").attr("font-weight","bold").attr("fill","black").text("Edges:"+TotalEdges_displayed);a.append("text").attr("x",0).attr("y",110).attr("dy","1.2em").style("text-anchor","start").attr("font-size","16px").attr("font-weight","bold").attr("fill",
"black").text("Cross Edges:"+TotalCEdges_displayed)};