function chorddiagram(){spinner.spin(document.getElementById("vis"));inalledge=drawonlycrossedge=clickednodes_check=!1;inoverview=!0;inexploredet=!1;$("#dragging").prop("checked",!1).change();$("#dragging").attr("disabled","disabled");dragging=!1;$("#zooming").prop("checked",!1).change();$("#zooming").attr("disabled","disabled");zooming=!1;$("#zooming2").prop("checked",!1).change();$("#zooming2").attr("disabled","disabled");$("#zooming3").prop("checked",!1).change();$("#zooming3").attr("disabled",
"disabled");$("#mousehighlight").prop("checked",!1).change();$("#mousehighlight").attr("disabled","disabled");$("#viewportedges").attr("disabled","disabled");$("#highlightcross").attr("disabled","disabled");reinitexploredetail();hide_details_controls();setTimeout(function(){$("#all")["0"].style.borderColor="#d43f3a";$("#clicked")["0"].style.borderColor="#d43f3a";$("#cross")["0"].style.borderColor="#d43f3a";$("#reset")["0"].style.borderColor="#d43f3a";$("#exploredet")["0"].style.borderColor="#d43f3a";
$("#chord")["0"].style.borderColor="#333";svg.select("#blocks").remove();svg.select("#edgesg").remove();svg.select("#genesg").remove();svg.select("#circle").remove();svg.select("#stackbar").remove();d3.select("#topg").attr("transform","translate(0,0)");generatechord(chord,chordforhover);spinner.stop()},1)}
function alledges(){var a=(new Date).getTime();spinner.spin(document.getElementById("vis"));swappingcheck_alledge&&updategeneinfo();drawonlycrossedge=clickednodes_check=!1;inalledge=!0;inexploredet=inoverview=!1;nodename="";$("#dragging").prop("checked",!1).change();$("#dragging").attr("disabled","disabled");dragging=!1;$("#zooming").prop("checked",!1).change();$("#zooming").attr("disabled","disabled");zooming=!1;$("#zooming2").prop("checked",!1).change();$("#zooming2").attr("disabled","disabled");
$("#zooming3").prop("checked",!1).change();$("#zooming3").attr("disabled","disabled");$("#mousehighlight").prop("checked",!1).change();$("#mousehighlight").attr("disabled","disabled");$("#viewportedges").attr("disabled","disabled");$("#highlightcross").removeAttr("disabled");reinitexploredetail();hide_details_controls();setTimeout(function(){$("#clicked")["0"].style.borderColor="#d43f3a";$("#cross")["0"].style.borderColor="#d43f3a";$("#reset")["0"].style.borderColor="#d43f3a";$("#chord")["0"].style.borderColor=
"#d43f3a";$("#exploredet")["0"].style.borderColor="#d43f3a";$("#all")["0"].style.borderColor="#333";svg.select("#blocks").remove();svg.select("#edgesg").remove();svg.select("#genesg").remove();svg.select("#circle").remove();svg.select("#stackbar").remove();drawblocks();drawgenes(genesdata);drawedges(edgesdata);d3.select("#topg").attr("transform","translate("+translatetopg_val+",0)");var b=(new Date).getTime();console.log(b+" "+(b-a)/1E3);spinner.stop()},1)}
function clickednodesedges(){spinner.spin(document.getElementById("vis"));clickednodes_check=!0;doubleclickedrect=inexploredet=inoverview=inalledge=drawonlycrossedge=!1;nodename="";$("#dragging").removeAttr("disabled");$("#zooming").removeAttr("disabled");$("#zooming2").removeAttr("disabled");$("#zooming3").removeAttr("disabled");$("#mousehighlight").removeAttr("disabled");$("#viewportedges").removeAttr("disabled");$("#highlightcross").removeAttr("disabled");reinitexploredetail();hide_details_controls();
setTimeout(function(){$("#all")["0"].style.borderColor="#d43f3a";$("#cross")["0"].style.borderColor="#d43f3a";$("#reset")["0"].style.borderColor="#d43f3a";$("#chord")["0"].style.borderColor="#d43f3a";$("#exploredet")["0"].style.borderColor="#d43f3a";$("#clicked")["0"].style.borderColor="#333";svg.select("#edgesg").remove();svg.select("#genesg").remove();svg.select("#circle").remove();svg.select("#stackbar").remove();svg.selectAll(".zoomi").attr("transform",d3.zoomIdentity);svg.attr("transform",d3.zoomIdentity);
zoom.scale(1);zoom.translate([0,0]);drawblocks();d3.select("#topg").attr("transform","translate("+translatetopg_val+",0)");spinner.stop()},1)}
function crossedges(){var a=(new Date).getTime();spinner.spin(document.getElementById("vis"));clickednodes_check=!1;drawonlycrossedge=!0;inexploredet=inoverview=inalledge=!1;nodename="";$("#dragging").prop("checked",!1).change();$("#dragging").attr("disabled","disabled");dragging=!1;$("#mousehighlight").prop("checked",!1).change();$("#mousehighlight").removeAttr("disabled");$("#highlightcross").prop("checked",!1).change();$("#highlightcross").attr("disabled","disabled");$("#zooming").removeAttr("disabled");
$("#zooming2").removeAttr("disabled");$("#zooming3").removeAttr("disabled");$("#viewportedges").removeAttr("disabled");reinitexploredetail();hide_details_controls();setTimeout(function(){$("#all")["0"].style.borderColor="#d43f3a";$("#clicked")["0"].style.borderColor="#d43f3a";$("#reset")["0"].style.borderColor="#d43f3a";$("#chord")["0"].style.borderColor="#d43f3a";$("#exploredet")["0"].style.borderColor="#d43f3a";$("#cross")["0"].style.borderColor="#333";svg.select("#blocks").remove();svg.select("#edgesg").remove();
svg.select("#genesg").remove();svg.select("#circle").remove();svg.select("#stackbar").remove();svg.selectAll(".zoomi").attr("transform",d3.zoomIdentity);svg.attr("transform",d3.zoomIdentity);d3.select("#topg").attr("transform","translate("+translatetopg_val+",0)");zoom.scale(1);zoom.translate([0,0]);drawblocks();if(swappingcheck_alledge){var b=filter_cross(edgesdata);drawgenes_cross(b[1]);drawedges_cross(b[0])}else drawgenes_cross(genes_cross_data),drawedges_cross(edge_cross_data);b=(new Date).getTime();
console.log(b+" "+(b-a)/1E3);spinner.stop()},5)}
function filter_cross(a){var b=[],c=[],f=[];a.forEach(function(a){var e=chrnames.indexOf(genesinfo[a.source].species),d=chrnames.indexOf(genesinfo[a.target].species);-1==e||-1==d||1<Math.abs(d-e)||Math.abs(genesinfo[a.target].ypos-genesinfo[a.source].ypos)<crossedge_threshold||(e={source:a.source,target:a.target},b.push(e),f.includes(a.source)||(f.push(a.source),e={Chr:genesinfo[a.source].Chr,Gene:a.source,Start:genesinfo[a.source].Start,End:genesinfo[a.source].End},c.push(e)),f.includes(a.target)||
(f.push(a.target),e={Chr:genesinfo[a.target].Chr,Gene:a.target,Start:genesinfo[a.target].Start,End:genesinfo[a.target].End},c.push(e)))});return[b,c]}
function resetfunc(){spinner.spin(document.getElementById("vis"));inexploredet=inoverview=inalledge=doubleclickedrect=drawonlycrossedge=clickednodes_check=!1;nodename="";setTimeout(function(){$("#all")["0"].style.borderColor="#d43f3a";$("#cross")["0"].style.borderColor="#d43f3a";$("#clicked")["0"].style.borderColor="#d43f3a";$("#chord")["0"].style.borderColor="#d43f3a";$("#exploredet")["0"].style.borderColor="#d43f3a";$("#reset")["0"].style.borderColor="#333";reinitexploredetail();hide_details_controls();
svg.select("#edgesg").remove();svg.select("#genesg").remove();svg.select("#circle").remove();svg.select("#stackbar").remove();svg.selectAll(".zoomi").attr("transform",d3.zoomIdentity);d3.select("#topg").attr("transform","translate("+translatetopg_val+",0)");zoom.scale(1);zoom.translate([0,0]);drawblocks();spinner.stop()},1)}
function getScreenBounds(){function a(a,c){var b=svg.node(),d=(b.ownerSVGElement||b).createSVGPoint();d.x=a;d.y=c;return d=d.matrixTransform(b.getScreenCTM().inverse())}return[a(0,0).x,a(0,0).y,a(width,height).x,a(width,height).y]}
function zz(){var a=d3.event;clickednodes_check&&zooming&&(svg.selectAll(".zoomi").attr("transform",["translate("+[0,zoom.translate()[1]]+")","scale("+[1,a.scale]+")"].join(" ")),1<a.scale?svg.selectAll(".blocktext").attr("opacity","0"):svg.selectAll(".blocktext").attr("opacity","1"))}
function addCheckbox(a){var b=$("#drop"),c=b.find("input").length+1,f=colorarr2[genetodna[a]];b=$("<li />",{id:c,style:"width:165px ; text-align:left;"}).appendTo(b);$("<input />",{type:"checkbox",id:"cb"+c,value:a,style:"display: inline-block; margin-left:20px;vertical-align: sub;    width: 15px;height: 15px;"}).appendTo(b);$("<label />",{"for":"cb"+c,text:a,"class":"check",style:"display: inline-block;padding: 0px 0px; font-weight: bold;color:"+f+";min-width: 125px;    margin-left: 5px; margin-bottom: 0px;"}).appendTo(b)}
function reinitexploredetail(){$("#drop").empty();for(var a=Object.keys(numbertochr),b=0;b<a.length;b++)addCheckbox(numbertochr[a[b]]);$(".checkbox-menu22").on("change","input[type='checkbox']",function(){$(this).closest("li")["0"].style.backgroundColor="#5aa8f6";$(this).prop("checked")?$("#exploredet").html("Explore Details: "+$(this).val()+' <span class="caret"></span>'):($("#exploredet").html('Explore Details <span class="caret"></span>'),$(this).closest("li")["0"].style.backgroundColor="transparent")});
$("input:checkbox").click(function(){$("input:checkbox").not(".checkbox.checkbox-danger").not(this).prop("checked",!1);for(var a=$("input:checkbox").not(".checkbox.checkbox-danger").not(this).closest("li"),b=0;b<a.length;b++)a[b].style.backgroundColor="transparent"});$("#exploredet").html('Explore Details <span class="caret"></span>')}
function onexploredetail(a,b){spinner.spin(document.getElementById("vis"));$("#all")["0"].style.borderColor="#d43f3a";$("#cross")["0"].style.borderColor="#d43f3a";$("#clicked")["0"].style.borderColor="#d43f3a";$("#chord")["0"].style.borderColor="#d43f3a";$("#reset")["0"].style.borderColor="#d43f3a";$("#exploredet")["0"].style.borderColor="#333";inoverview=inalledge=doubleclickedrect=drawonlycrossedge=clickednodes_check=!1;inexploredet=!0;$("#dragging").prop("checked",!1).change();$("#dragging").attr("disabled",
"disabled");dragging=!1;$("#zooming").removeAttr("disabled");$("#zooming2").removeAttr("disabled");$("#zooming3").removeAttr("disabled");$("#mousehighlight").removeAttr("disabled");$("#viewportedges").removeAttr("disabled");$("#highlightcross").removeAttr("disabled");"check"==b?(nodename="",exploredet_name=a,explore_detail(a),spinner.stop()):"uncheck"==b&&(inoverview=inalledge=doubleclickedrect=drawonlycrossedge=clickednodes_check=!1,exploredet_name=nodename="",setTimeout(function(){svg.select("#edgesg").remove();
svg.select("#genesg").remove();svg.select("#circle").remove();svg.select("#stackbar").remove();svg.select("#blocks").remove();svg.selectAll(".zoomi").attr("transform",d3.zoomIdentity);d3.select("#topg").attr("transform","translate("+translatetopg_val+",0)");zoom.scale(1);zoom.translate([0,0]);spinner.stop()},1))}
function colorthemechange(a){function b(a){if("t1"==a)return c;if("t2"==a)return f;if("t3"==a)return d}var c=["rgb(255, 182, 18)","#4682B4"," #BA55D3","#3CB371"],f=["#b33040e6","#B8860Bbd","#C71585db","#6B8E23"],d=["#00CED1","#FF5722bd","#CD853F","#DA70D6"];"t1"==a.value?(color1=c[0],color2=c[1],color3=c[2],color4=c[3]):"t2"==a.value?(color1=f[0],color2=f[1],color3=f[2],color4=f[3]):"t3"==a.value&&(color1=d[0],color2=d[1],color3=d[2],color4=d[3]);for(var e=1;4>=e;e++){var g=colorarr[e];-1!=c.indexOf(g)?
colorarr[e]=b(a.value)[c.indexOf(g)]:-1!=f.indexOf(g)?colorarr[e]=b(a.value)[f.indexOf(g)]:-1!=d.indexOf(g)&&(colorarr[e]=b(a.value)[d.indexOf(g)])}colorarr2.Barley=color1;colorarr2.WheatA=color2;colorarr2.WheatB=color3;colorarr2.WheatD=color4;updategeneinfo();reinitexploredetail();inoverview?chorddiagram():inalledge?alledges():drawonlycrossedge?crossedges():clickednodes_check?!check_doubleclickrect&&nodename&&1<nodename.length?chrclicked(nodename):check_doubleclickrect&&nodename&&1<nodename.length?
chrdblclicked(nodename):clickednodesedges():inexploredet?(explore_detail(exploredet_name),$("#exploredet").html("Explore Details: "+exploredet_name+' <span class="caret"></span>')):resetfunc()}var counter=0;function animateFirstSteprect(a){a.transition().delay(0).duration(1E3).attr("fill-opacity",1).style("stroke-width",highlighted_edge_stroke_width).style("stroke",genehighlightcolor).each("end",function(a,c){counter++;5>counter?d3.select(this).call(animateSecondSteprect):counter=0})}
function animateSecondSteprect(a){a.transition().delay(0).duration(1E3).attr("fill-opacity",gene_opcaity).style("stroke-width","0px").style("stroke","none").each("end",function(a,c){d3.select(this).call(animateFirstSteprect)})};