function generatechord(g,e){svg.select("#blocks").remove();svg.select("#edgesg").remove();svg.select("#genesg").remove();svg.select("#analyticsg").remove();svg.select("#circle").remove();svg.select("#stackbar").remove();svg.selectAll("linearGradient").remove();var h=height-0,d=Math.min(width-0,h)/2-100,k=d-28,r=d3.format(".1f"),c=d3.svg.arc().innerRadius(k).outerRadius(d),l=customChordLayout().padding(.05).sortSubgroups(d3.descending).sortChords(d3.ascending),n=d3.svg.chord().radius(k-7),m=svg.append("g").attr("id",
"circle").attr("transform","translate("+(d+100)+","+(h/2+45)+")");m.append("text").attr("class","textnumbers").attr("x",0).attr("y",-(h/2)-34).attr("dy","1.2em").style("text-anchor","middle").attr("font-size","28px").attr("font-weight","bold").attr("fill","indianred").text("Chord Diagram");m.append("text").attr("class","textnumbers").attr("x",0).attr("y",-(h/2)).attr("dy","1.2em").style("text-anchor","middle").attr("font-size","20px").attr("fill","indianred").text("(Showing All Genes Relationships)");
m.append("circle").attr("r",d).style("fill","none");d3.csv("species-oceanic.csv",function(f){function d(a){return"linkGrad-"+a.source.index+"-"+a.target.index}l.matrix(g);var b=svg.append("defs").selectAll("linearGradient").data(l.chords()).enter().append("linearGradient").attr("id",d).attr("gradientUnits","userSpaceOnUse").attr("x1",function(a,b){return k*Math.cos((a.source.endAngle-a.source.startAngle)/2+a.source.startAngle-Math.PI/2)}).attr("y1",function(a,b){return k*Math.sin((a.source.endAngle-
a.source.startAngle)/2+a.source.startAngle-Math.PI/2)}).attr("x2",function(a,b){return k*Math.cos((a.target.endAngle-a.target.startAngle)/2+a.target.startAngle-Math.PI/2)}).attr("y2",function(a,b){return k*Math.sin((a.target.endAngle-a.target.startAngle)/2+a.target.startAngle-Math.PI/2)});b.append("stop").attr("offset","0%").attr("stop-color",function(a){return colorarr2[genetodna[f[a.source.index].name]]});b.append("stop").attr("offset","100%").attr("stop-color",function(a){return colorarr2[genetodna[f[a.target.index].name]]});
b=m.selectAll(".group").data(l.groups).enter().append("g").attr("class","group").on("mouseover",function(a,b){syncmousehover(d3.select(this).select("title")[0][0].innerHTML);svg.selectAll("path.chord").filter(function(a){return a.source.index!==b&&a.target.index!==b}).transition().style("opacity",.15)}).on("mouseout",function(a,b){syncmouseout(d3.select(this).select("title")[0][0].innerHTML);svg.selectAll("path.chord").transition().style("opacity",1)});b.append("title").text(function(a,b){return f[b].name});
b.append("path").attr("id",function(a,b){return"group"+b}).attr("d",c).style("fill",function(a,b){return colorarr2[genetodna[f[b].name]]}).style("stroke",function(a,b,q){return"black"}).style("stroke-width",function(a,b){return"1px"});b.append("text").attr("dy",25);b.append("svg:text").each(function(a,b){a.angle=(a.startAngle+a.endAngle)/2}).attr("dy",".35em").attr("text-anchor",function(a){return a.angle>Math.PI?"end":null}).attr("transform",function(a){return"rotate("+(180*a.angle/Math.PI-90)+")translate("+
(k+33)+")"+(a.angle>Math.PI?"rotate(180)":"")}).text(function(a,b){return f[b].name}).style("fill",function(a,b){return colorarr2[genetodna[f[b].name]]}).attr("shape-rendering","crispEdges").attr("font-family","Arial").attr("font-size","20px");m.selectAll(".chord").data(l.chords).enter().append("path").attr("class","chord").style("fill",function(a,b){var q=f[a.source.index].name.charAt(2),c=f[a.target.index].name.charAt(2);return q==c?"url(#"+d(a)+")":"red"}).style("fill-opacity",function(a){return 200>
a.source.value?1:.6}).style("stroke",function(a,b){var q=f[a.source.index].name.charAt(2),c=f[a.target.index].name.charAt(2);return q==c?"#800000":"red"}).style("stroke-opacity",function(a,b){var q=f[a.source.index].name.charAt(2),c=f[a.target.index].name.charAt(2);return q==c?"0.7":"1"}).style("stroke-width",function(a,b){var c=f[a.source.index].name.charAt(2),d=f[a.target.index].name.charAt(2);c==d?(c=chord_crossedges[a.source.index][a.target.index],c=(50>c?"1":50<=c&&100>c?"1.5":100<=c&&300>c?
"2":300<=c&&500>c?"3":500<=c&&1E3>c?"4":"5")+"px"):c="1px";return c}).attr("d",n).on("mouseover",function(a,b){svg.selectAll("path.chord").transition().style("opacity",.15);d3.select(this).transition().style("opacity",1);var c=f[a.source.index].name,d=f[a.target.index].name;svg.selectAll("g.cost").selectAll("rect").style("opacity",function(a,b){return a.x==c&&a.x2==d||a.x2==c&&a.x==d?1:.1})}).on("mouseout",function(a,b){svg.selectAll("path.chord").transition().style("opacity",1);svg.selectAll("g.cost").selectAll("rect").style("opacity",
function(a,b){return 1})}).append("title").text(function(a){return f[a.source.index].name+" <-> "+f[a.target.index].name+": "+r(e[a.source.index][a.target.index])+" connections, "+chord_crossedges[a.source.index][a.target.index]+" cross connections"})});gensbc(d)}var xAxisG;
function syncmousehover(g){xAxisG.selectAll(".tick").filter(function(e){e==g&&(d3.select(this).selectAll("text").style("font-size","28px").style("fill","red"),svg.selectAll("g.cost").selectAll("rect").style("opacity",function(e,d){if(e.x!=g)return.1}))})}
function syncmouseout(g){xAxisG.selectAll(".tick").filter(function(e){e==g&&(d3.select(this).selectAll("text").style("font-size","20px").style("text-anchor","end").style("font-family","Arial").style("shape-rendering","crispEdges").style("fill",function(e){return colorarr2[[genetodna[e]]]}),svg.selectAll("g.cost").selectAll("rect").style("opacity",function(e,d){return 1}))})}
function sync2mousehover(g){svg.selectAll("path.chord").filter(function(e,h){return e.source.index!==chrtonumber[g]&&e.target.index!==chrtonumber[g]}).transition().style("opacity",.15)}function sync2mouseout(g){svg.selectAll("path.chord").transition().style("opacity",1)}
function gensbc(g){var e=width-90-50-2*(g+100),h=height-100-80,d=svg.append("g").attr("id","stackbar").attr("width",e).attr("transform","translate("+(2*(g+100)+50)+",100)");d.append("text").attr("x",e/2).attr("y",-92).attr("dy","1.2em").style("text-anchor","middle").attr("font-size","28px").attr("font-weight","bold").attr("fill","indianred").text("Stacked Bar Charts");d.append("text").attr("x",e/2).attr("y",-62).attr("dy","1.2em").style("text-anchor","middle").attr("font-size","20px").attr("fill",
"indianred").text("(Showing Only Cross Genes Relationships)");var k=sbcdata,r=[color1,color1,color1,color1,color1,color1,color1,color2,color2,color2,color2,color2,color2,color2,color3,color3,color3,color3,color3,color3,color3,color4,color4,color4,color4,color4,color4,color4],c="hv1H hv2H hv3H hv4H hv5H hv6H hv7H ta1A ta2A ta3A ta4A ta5A ta6A ta7A ta1B ta2B ta3B ta4B ta5B ta6B ta7B ta1D ta2D ta3D ta4D ta5D ta6D ta7D".split(" ");g=d3.layout.stack()(c.map(function(b){return k.map(function(a){return{x:a.year,
y:+a[b],x2:b}})}));var l=d3.scale.ordinal().domain(g[0].map(function(b){return b.x})).rangeRoundBands([1,e-1],.2),n=d3.scale.linear().domain([0,d3.max(g,function(b){return d3.max(b,function(a){return a.y0+a.y})})]).range([h,0]),m=d3.svg.axis().scale(n).orient("left").ticks(5).tickSize(-e,0,0).tickFormat(function(b){return b}),f=d3.svg.axis().scale(l).orient("bottom");d.append("g").attr("class","y axis").call(m);xAxisG=d.append("g").attr("class","x axis").attr("transform","translate(0,"+h+")").call(f);
xAxisG.selectAll("text").attr("y",0).attr("x",-10).attr("dy",".35em").attr("transform","rotate(-90)").style("text-anchor","end").style("font-family","Arial").style("font-size","20px").style("shape-rendering","crispEdges").attr("fill",function(b){return colorarr2[[genetodna[b]]]});xAxisG.selectAll(".tick").on("mouseover",function(b){sync2mousehover(b);d3.select(this).selectAll("text").style("font-size","28px").style("fill","red");d.selectAll("g.cost").selectAll("rect").style("opacity",function(a,c){if(a.x!=
b)return.1})}).on("mouseout",function(b){sync2mouseout(b);d3.select(this).selectAll("text").style("font-size","20px").style("text-anchor","end").style("font-family","Arial").style("shape-rendering","crispEdges").style("fill",function(a){return colorarr2[[genetodna[a]]]});d.selectAll("g.cost").selectAll("rect").style("opacity",function(a,b){return 1})});d.selectAll("g.cost").data(g).enter().append("g").attr("class","cost").style("fill",function(b,a){return r[a]}).selectAll("rect").data(function(b){return b}).enter().append("rect").attr("x",
function(b){return l(b.x)}).attr("y",function(b){return n(b.y0+b.y)}).attr("height",function(b){return n(b.y0)-n(b.y0+b.y)}).attr("width",l.rangeBand()).attr("stroke","black").attr("stroke-width",".5px").attr("stroke-opacity",".5").on("mouseover",function(b,a){d3.select(this).moveToFront();d3.select(this).attr("stroke","red");d3.select(this).attr("stroke-width","4px");d3.select(this).attr("stroke-opacity","1");p.style("display",null);var c=chrtonumber[b.x],d=chrtonumber[b.x2];svg.selectAll("path.chord").filter(function(a){return!(a.source.index==
c&&a.target.index==d||a.source.index==d&&a.target.index==c)}).transition().style("opacity",.15)}).on("mouseout",function(b,a){d3.select(this).attr("stroke","black");d3.select(this).attr("stroke-width",".5px");d3.select(this).attr("stroke-opacity","0.5");p.style("display","none");svg.selectAll("path.chord").transition().style("opacity",1)}).on("mousemove",function(b){var a=d3.mouse(this)[0]-15,c=d3.mouse(this)[1]-35;p.attr("transform","translate("+a+","+c+")");p.select("text").text(b.y+" "+b.x+" <--\x3e "+
b.x2+" cross genes connections")});h=d.selectAll(".legend").data(r).enter().append("g").attr("class","legend").attr("transform",function(b,a){return"translate(30,"+19*a+")"});h.append("rect").attr("x",e-18).attr("width",18).attr("height",18).style("fill",function(b,a){return r.slice().reverse()[a]}).on("mouseover",function(b,a){syncmousehover(c[c.length-a-1]);sync2mousehover(c[c.length-a-1])}).on("mouseout",function(b,a){syncmouseout(c[c.length-a-1]);sync2mouseout(c[c.length-a-1])});h.append("text").attr("x",
e+5).attr("y",9).attr("dy",".35em").style("text-anchor","start").style("font-family","Arial").style("font-size","14px").style("shape-rendering","crispEdges").attr("fill",function(b,a){return colorarr2[[genetodna[c[c.length-a-1]]]]}).text(function(b,a){return c[c.length-a-1]}).on("mouseover",function(b,a){syncmousehover(c[c.length-a-1]);sync2mousehover(c[c.length-a-1])}).on("mouseout",function(b,a){syncmouseout(c[c.length-a-1]);sync2mouseout(c[c.length-a-1])});var p=d.append("g").attr("class","tooltip222").style("display",
"none");p.append("rect").attr("width",100).attr("height",30).attr("fill","transparent").style("opacity",.5);p.append("text").attr("x",15).attr("dy","1.2em").style("text-anchor","middle").attr("font-size","18px").attr("fill","crimson")};