function drawdata_rem(d){spinner.spin(document.getElementById("vis"));setTimeout(function(){svg.select("#edgesg")&&svg.select("#edgesg").remove();svg.select("#genesg")&&svg.select("#genesg").remove();svg.selectAll(".zoomi").attr("transform",d3.zoomIdentity);svg.attr("transform",d3.zoomIdentity);d3.select("#topg").attr("transform","translate("+translatetopg_val+",0)");zoom.scale(1);zoom.translate([0,0]);drawblocks_det();drawfiltergenes_det_rem(genesdata,d);drawfilteredges_det_rem(edgesdata,d);spinner.stop()},
1)}
function drawfiltergenes_det_rem(d,b){chrnames.indexOf(genetodna[b]);var a=chrtogenesneighbor[b];a=a.concat(chrtogenes[b]);for(var e=[],c=0;c<a.length;c++)details_selcb.includes(genesinfo[a[c]].Chr)||!chrtorelchr.includes(genesinfo[a[c]].Chr)&&genesinfo[a[c]].Chr!=exploredet_name||e.push({Chr:genesinfo[a[c]].Chr,Gene:a[c],Start:genesinfo[a[c]].Start,End:genesinfo[a[c]].End});TotalGenes_displayed=e.length;text=svg.append("g").attr("id","genesg").selectAll("rect").data(e).enter().append("rect").attr("id",function(a){return a.Gene.replace(".",
"_")}).attr("transform",transform_det).attr("width",rectwidth-2).attr("height",function(a){return genesinfo[a.Gene].returnposheight*zoom.scale()}).attr("fill",function(a){return genesinfo[a.Gene].color}).attr("fill-opacity",gene_opcaity).attr("class","nodes").on("mouseover",nodemouseover2).on("mouseout",nodemouseout2).on("click",function(a,c){var d="",b=new XMLHttpRequest;b.onreadystatechange=function(){if(200==b.status&&4==b.readyState){d=b.responseText;var c=window.open("","_blank","left=0,top=0,width=700,height=700");
c.document.write("<title>Gene Detail</title> <center><b><h2>"+a.Gene+"</b></h2></center>  <br /><br /><p>"+d+"</p>");c.document.close()}};b.open("GET","samplegene.txt",!0);b.send()});text2=text.append("svg:title").text(function(a){return a.Gene+"\n"})}
function drawfilteredges_det_rem(d,b){for(var a=chrtogenes[b],e=[],c=0;c<a.length;c++){var f=genesneighbours[a[c]],g=a[c];if(f)for(var h=0;h<f.length;h++){var k=f[h];chrnames.indexOf(genesinfo[g].species);chrnames.indexOf(genesinfo[k].species);e.push({source:g,target:k})}}var l=0;svg.append("g").attr("id","edgesg").selectAll("links23").data(e).enter().append("path").attr("class","links23").attr("d",function(a){return link_det_rem(a)}).style("stroke-width",function(a){return Math.abs(genesinfo[a.target].ypos-
genesinfo[a.source].ypos)>crossedge_threshold?(l++,highlightcrossedges?stroke_width_cross_highlight:stroke_width_cross):stroke_width_straight}).style("stroke",function(a,b){return genesinfo[a.target].color}).style("fill","transparent").style("opacity",function(a){return Math.abs(genesinfo[a.target].ypos-genesinfo[a.source].ypos)>crossedge_threshold?$("#detail_crossedges").prop("checked")?stroke_opacity_cross_highlight:highlightcrossedges?stroke_opacity_cross_highlight:stroke_opacity_cross:$("#detail_crossedges").prop("checked")?
0:stroke_opacity_straight}).on("mouseover",edgemouseover).on("mouseout",edgemouseout).attr("id",function(a){return a.source.replace(".","_")+""+a.target.replace(".","_")}).append("svg:title").text(function(a){return a.source+" "+a.target});svg.select("#edgesg").moveToBack();TotalEdges_displayed=e.length;TotalCEdges_displayed=l;analytics()}
function link_det_rem(d){if(svg.select("#"+genesinfo[d.source].Chr)["0"]["0"]){var b=svg.select("#"+genesinfo[d.source].Chr)["0"]["0"].attributes[8].value;if(svg.select("#"+genesinfo[d.target].Chr)["0"]["0"]){var a=svg.select("#"+genesinfo[d.target].Chr)["0"]["0"].attributes[8].value;b=b.slice(9,b.length);var e=+b.slice(1,b.indexOf(","));a=a.slice(9,a.length);var c=+a.slice(1,a.indexOf(","));b=svg.select("#"+d.source.replace(".","_"))["0"]["0"].transform.animVal["0"].matrix.f;a=svg.select("#"+d.target.replace(".",
"_"))["0"]["0"].transform.animVal["0"].matrix.f;var f=svg.select("#"+d.source.replace(".","_"))["0"]["0"].transform.animVal["0"].matrix.e,g=svg.select("#"+d.target.replace(".","_"))["0"]["0"].transform.animVal["0"].matrix.e;if(!showviewportonlyedges||!(0>b||b>height||0>a||a>height)){if(e<c)return d=+f+rectwidth-1,e=+g-1,f=d3.interpolateNumber(d,e),c=f(curvature),f=f(1-curvature),"M"+d+","+b+"C"+c+","+b+" "+f+","+a+" "+e+","+a;if(c<e)return d=+f-1,e=+g+rectwidth-1,f=d3.interpolateNumber(d,e),c=f(curvature),
f=f(1-curvature),"M"+d+","+b+"C"+c+","+b+" "+f+","+a+" "+e+","+a}}}};